Makefile: Fix link error for `UCKeyTranslate`
The linker complained about `_UCKeyTranslate` being undefined. It's used
by DDHotKey, and is defined in `CoreServices.framework`, so we need to
link CoreServices.

Here's the error I was getting:

    clang -x objective-c \
        -mmacosx-version-min=10.7 \
        -framework Carbon \
        -framework Cocoa \
        -framework CoreGraphics \
        -framework Foundation \
        -fno-objc-arc \
        -I./build/include \
        -L./build \
        -lddhotkey \
        -o invert-catalina-invert \
        Invert.h Invert.m main.m
    Undefined symbols for architecture x86_64:
      "_UCKeyTranslate", referenced from:
          _DDStringFromKeyCode in libddhotkey.a(DDHotKeyUtilities.o)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)